apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-app
  namespace: jaeger
  labels:
    com.service: jaeger-app
    com.company: glasswall
    com.product: go-lang
    com.stage: dev
    com.team: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      com.service: jaeger-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        com.service: jaeger-app
        com.company: glasswall
        com.product: go-lang
        com.stage: dev
        com.team: devops
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: jaeger-agent
        image: jaegertracing/all-in-one:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 0.5
            memory: 500M
          requests:
            cpu: 0.5
            memory: 500M
        ports:
          - containerPort: 5775
          - containerPort: 6831
          - containerPort: 6832
          - containerPort: 5778
          - containerPort: 16686
          - containerPort: 14268
          - containerPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  ports:
  - name: agent-zipkin-thrift
    port: 5775
    protocol: UDP
    targetPort: 5775
  - name: agent-compact
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: agent-binary
    port: 6832
    protocol: UDP
    targetPort: 6832
  - name: agent-configs
    port: 5778
    protocol: TCP
    targetPort: 5778
  - name: query-http
    port: 80
    protocol: TCP
    targetPort: 16686
  - name: jaeger-collector-http
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: jaeger-collector-zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    com.service: jaeger-app
  sessionAffinity: None
  type: ClusterIP
