environment:
podcontroller:
  name: pod-controller
  namespace: icap-adaptation
  rolename: pod-controller-role
  saname: pod-controller-sa
  replicas: 1
  processimage: himanshu2464/go-k8s-process:v2
srv1:
  name: srv1
  replicas: 1
srv2:
  name: srv2
  replicas: 1
queue:
  adaptationRequest:
    hostname: "rabbitmq-service"
    port: "\"5672\""
minio:
  adaptationRequest:
    endpoint: "minio-server.minio.svc.cluster.local:9000"
    sourcebucket: "sourcefiles"
    processedbucket: "cleanfiles"
imagestore:
  podcontroller:
    registry: ""
    repository: azopat/go-k8s-controller
    tag: latest
  srv1:
    registry: ""
    repository: himanshu2464/go-k8s-srv1
    tag: v2
  srv2:
    registry: ""
    repository: himanshu2464/go-k8s-srv2
    tag: v3
volumemountpath:
  source: "/var/source"
  target: "/var/target"
  transactions: /mnt/transactions
