name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up
        uses: actions/setup-go@v2

      - name: Build
        run: 'echo "Dummy Build ok"'

      - name: 'Test'
        run: 'echo "Dummy Test ok"'